title: My Portfolio
description: This is my personal portfolio site showcasing my projects and skills.
url: "https://github.com/Sinelisiwe/sineli.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-cayman 

author:
  name: "Sinelisiwe Sibeko"
  email: "sinelisibeko@gmail.com"
